-- =========================================================
-- TECH DEVICE RENTAL DATABASE - SUPABASE / POSTGRESQL
-- Đã gộp Invoices vào Rental Orders & Loại bỏ mọi cấu trúc đệ quy
-- Tách riêng hệ thống Reply cho Reviews
-- =========================================================


-- =========================================================
-- 0. DROP TABLES
-- =========================================================

DROP TABLE IF EXISTS maintenance_records CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS review_replies CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS return_device_images CASCADE;
DROP TABLE IF EXISTS return_devices CASCADE;
DROP TABLE IF EXISTS return_records CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_fees CASCADE;
DROP TABLE IF EXISTS rental_order_units CASCADE;
DROP TABLE IF EXISTS rental_order_details CASCADE;
DROP TABLE IF EXISTS rental_orders CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS device_images CASCADE;
DROP TABLE IF EXISTS device_units CASCADE;
DROP TABLE IF EXISTS device_variants CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS storage_capacities CASCADE;
DROP TABLE IF EXISTS colors CASCADE;
DROP TABLE IF EXISTS equipment_categories CASCADE;


-- =========================================================
-- 1. MASTER DATA: CATEGORY / COLOR / CAPACITY
-- =========================================================

-- Danh mục thiết bị (Đã bỏ đệ quy parent_category_id)
CREATE TABLE equipment_categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL,
    category_image TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bảng màu dùng chung
CREATE TABLE colors (
    color_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color_name VARCHAR(100) NOT NULL UNIQUE
);

-- Bảng dung lượng/cấu hình dùng chung
CREATE TABLE storage_capacities (
    capacity_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacity_value VARCHAR(100) NOT NULL UNIQUE
);


-- =========================================================
-- 2. PRODUCT: DEVICE / VARIANT / UNIT / IMAGE
-- =========================================================

-- Thiết bị ở mức model chung
CREATE TABLE devices (
    device_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_name VARCHAR(255) NOT NULL,
    manufacturer VARCHAR(255),
    description TEXT,
    default_image TEXT,
    category_id INT REFERENCES equipment_categories(category_id) ON DELETE SET NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Phiên bản của thiết bị
CREATE TABLE device_variants (
    variant_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INT NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
    color_id INT REFERENCES colors(color_id) ON DELETE RESTRICT,
    capacity_id INT REFERENCES storage_capacities(capacity_id) ON DELETE RESTRICT,
    condition_name VARCHAR(100) NOT NULL DEFAULT 'New',
    daily_rental_price NUMERIC(12, 2) NOT NULL CHECK (daily_rental_price >= 0),
    deposit_amount NUMERIC(12, 2) NOT NULL CHECK (deposit_amount >= 0),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (device_id, color_id, capacity_id, condition_name)
);

-- Thiết bị vật lý thật trong kho
CREATE TABLE device_units (
    unit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id INT NOT NULL REFERENCES device_variants(variant_id) ON DELETE CASCADE,
    unit_code VARCHAR(100) NOT NULL UNIQUE,
    serial_number VARCHAR(100) UNIQUE,
    imei VARCHAR(100) UNIQUE,
    current_status VARCHAR(50) NOT NULL DEFAULT 'available',
    current_condition VARCHAR(100) DEFAULT 'Good',
    purchase_price NUMERIC(12, 2) CHECK (purchase_price IS NULL OR purchase_price >= 0),
    purchase_date DATE,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (current_status IN (
        'available', 'reserved', 'rented', 'maintenance', 'lost', 'retired'
    ))
);

-- Ảnh thiết bị
CREATE TABLE device_images (
    image_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INT NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
    color_id INT REFERENCES colors(color_id) ON DELETE SET NULL,
    image_url TEXT NOT NULL,
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 3. USER: CUSTOMER / STAFF
-- =========================================================

-- Khách hàng
CREATE TABLE customers (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    email VARCHAR(255) UNIQUE,
    address TEXT,
    password_hash VARCHAR(255),
    identity_number VARCHAR(50),
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (status IN ('active', 'locked', 'deleted'))
);

-- Nhân viên (Đã bỏ đệ quy manager_id)
CREATE TABLE staff (
    staff_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255),
    position_name VARCHAR(100),
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (status IN ('active', 'locked', 'deleted'))
);


-- =========================================================
-- 4. RENTAL ORDER (MERGED WITH INVOICE)
-- =========================================================

-- Đơn thuê gộp chung dữ liệu Hóa Đơn (Tài chính & Thanh toán)
CREATE TABLE rental_orders (
    rental_order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code VARCHAR(50) UNIQUE,
    customer_id INT REFERENCES customers(customer_id) ON DELETE SET NULL,
    staff_id INT REFERENCES staff(staff_id) ON DELETE SET NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    rental_start_date DATE NOT NULL,
    expected_return_date DATE NOT NULL,
    
    -- Trạng thái đơn hàng
    rental_order_status VARCHAR(50) DEFAULT 'pending',
    
    -- Dữ liệu tài chính (Từ bảng Invoices cũ)
    subtotal_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (subtotal_amount >= 0),
    deposit_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (deposit_amount >= 0),
    penalty_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (penalty_amount >= 0),
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    payment_status VARCHAR(50) DEFAULT 'unpaid',
    
    note TEXT,

    CHECK (expected_return_date >= rental_start_date),
    CHECK (rental_order_status IN ('pending', 'confirmed', 'active', 'completed', 'cancelled')),
    CHECK (payment_status IN ('unpaid', 'partial_paid', 'paid', 'refunded', 'cancelled'))
);

-- Chi tiết đơn thuê theo variant
CREATE TABLE rental_order_details (
    rental_order_detail_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_order_id INT NOT NULL REFERENCES rental_orders(rental_order_id) ON DELETE CASCADE,
    variant_id INT NOT NULL REFERENCES device_variants(variant_id) ON DELETE RESTRICT,
    rental_days INT NOT NULL CHECK (rental_days > 0),
    rental_quantity INT NOT NULL DEFAULT 1 CHECK (rental_quantity > 0),
    unit_rental_price NUMERIC(12, 2) NOT NULL CHECK (unit_rental_price >= 0),
    unit_deposit_amount NUMERIC(12, 2) NOT NULL CHECK (unit_deposit_amount >= 0),
    line_note TEXT,

    UNIQUE (rental_order_id, variant_id)
);

-- Gán thiết bị vật lý thật cho dòng đơn thuê
CREATE TABLE rental_order_units (
    rental_order_unit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_order_detail_id INT NOT NULL REFERENCES rental_order_details(rental_order_detail_id) ON DELETE CASCADE,
    unit_id INT NOT NULL REFERENCES device_units(unit_id) ON DELETE RESTRICT,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (rental_order_detail_id, unit_id)
);

-- Các loại phí cụ thể cho đơn hàng (Thay thế bảng invoice_items)
CREATE TABLE order_fees (
    order_fee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_order_id INT NOT NULL REFERENCES rental_orders(rental_order_id) ON DELETE CASCADE,
    fee_type VARCHAR(50) NOT NULL,
    description TEXT,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (fee_type IN ('rental_fee', 'deposit', 'penalty', 'damage_fee', 'refund', 'discount', 'other'))
);

-- Thanh toán cho Đơn Thuê
CREATE TABLE payments (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_order_id INT NOT NULL REFERENCES rental_orders(rental_order_id) ON DELETE CASCADE,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    payment_method VARCHAR(100),
    payment_type VARCHAR(50) DEFAULT 'payment',
    payment_status VARCHAR(50) DEFAULT 'pending',
    transaction_code VARCHAR(100),
    paid_at TIMESTAMP,
    note TEXT,

    CHECK (payment_type IN ('payment', 'deposit', 'penalty', 'refund')),
    CHECK (payment_status IN ('pending', 'paid', 'failed', 'cancelled', 'refunded'))
);


-- =========================================================
-- 5. RETURN DEVICE
-- =========================================================

-- Phiếu trả thiết bị
CREATE TABLE return_records (
    return_record_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_order_id INT REFERENCES rental_orders(rental_order_id) ON DELETE SET NULL,
    staff_id INT REFERENCES staff(staff_id) ON DELETE SET NULL,
    actual_return_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note TEXT
);

-- Thiết bị được trả theo từng unit_id
CREATE TABLE return_devices (
    return_device_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_record_id INT NOT NULL REFERENCES return_records(return_record_id) ON DELETE CASCADE,
    unit_id INT NOT NULL REFERENCES device_units(unit_id) ON DELETE RESTRICT,
    return_condition VARCHAR(100) DEFAULT 'Good',
    damage_description TEXT,
    late_days INT DEFAULT 0 CHECK (late_days >= 0),
    penalty_fee NUMERIC(12, 2) DEFAULT 0 CHECK (penalty_fee >= 0),

    UNIQUE (return_record_id, unit_id)
);

-- Ảnh bằng chứng khi trả thiết bị
CREATE TABLE return_device_images (
    image_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_device_id INT NOT NULL REFERENCES return_devices(return_device_id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 6. REVIEW & REPLIES
-- =========================================================

-- Đánh giá gốc từ Khách hàng (Đã bỏ đệ quy parent_review_id)
CREATE TABLE reviews (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
    rental_order_id INT REFERENCES rental_orders(rental_order_id) ON DELETE SET NULL,
    variant_id INT REFERENCES device_variants(variant_id) ON DELETE SET NULL,
    equipment_rating INT CHECK (equipment_rating IS NULL OR equipment_rating BETWEEN 1 AND 5),
    service_rating INT CHECK (service_rating IS NULL OR service_rating BETWEEN 1 AND 5),
    comment TEXT NOT NULL,
    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tách riêng bảng Phản hồi Đánh giá (Khách khác hoặc Nhân viên có thể trả lời)
CREATE TABLE review_replies (
    reply_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id INT NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
    customer_id INT REFERENCES customers(customer_id) ON DELETE SET NULL,
    staff_id INT REFERENCES staff(staff_id) ON DELETE SET NULL,
    reply_content TEXT NOT NULL,
    reply_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Chỉ cho phép 1 trong 2 người trả lời (nhân viên HOẶC khách hàng)
    CHECK (
        (customer_id IS NOT NULL AND staff_id IS NULL)
        OR
        (customer_id IS NULL AND staff_id IS NOT NULL)
    )
);


-- =========================================================
-- 7. CART / FAVORITES
-- =========================================================

-- Giỏ hàng
CREATE TABLE cart_items (
    cart_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255),
    customer_id INT REFERENCES customers(customer_id) ON DELETE CASCADE,
    variant_id INT NOT NULL REFERENCES device_variants(variant_id) ON DELETE CASCADE,
    quantity INT DEFAULT 1 CHECK (quantity > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (session_id IS NOT NULL OR customer_id IS NOT NULL)
);

-- Yêu thích
CREATE TABLE favorites (
    favorite_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255),
    customer_id INT REFERENCES customers(customer_id) ON DELETE CASCADE,
    variant_id INT NOT NULL REFERENCES device_variants(variant_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (session_id IS NOT NULL OR customer_id IS NOT NULL)
);

-- Partial Unique Index
CREATE UNIQUE INDEX unique_cart_guest ON cart_items (session_id, variant_id) WHERE customer_id IS NULL;
CREATE UNIQUE INDEX unique_cart_customer ON cart_items (customer_id, variant_id) WHERE customer_id IS NOT NULL;
CREATE UNIQUE INDEX unique_favorite_guest ON favorites (session_id, variant_id) WHERE customer_id IS NULL;
CREATE UNIQUE INDEX unique_favorite_customer ON favorites (customer_id, variant_id) WHERE customer_id IS NOT NULL;


-- =========================================================
-- 8. MAINTENANCE
-- =========================================================

-- Lịch sử bảo trì
CREATE TABLE maintenance_records (
    maintenance_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id INT NOT NULL REFERENCES device_units(unit_id) ON DELETE CASCADE,
    staff_id INT REFERENCES staff(staff_id) ON DELETE SET NULL,
    maintenance_type VARCHAR(100),
    description TEXT,
    cost NUMERIC(12, 2) DEFAULT 0 CHECK (cost >= 0),
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_date TIMESTAMP,
    maintenance_status VARCHAR(50) DEFAULT 'open',
    note TEXT,

    CHECK (maintenance_status IN ('open', 'in_progress', 'completed', 'cancelled'))
);


-- =========================================================
-- 9. INDEXES
-- =========================================================

CREATE INDEX idx_devices_category ON devices(category_id);
CREATE INDEX idx_devices_name ON devices(device_name);
CREATE INDEX idx_variants_device ON device_variants(device_id);
CREATE INDEX idx_variants_color ON device_variants(color_id);
CREATE INDEX idx_variants_capacity ON device_variants(capacity_id);
CREATE INDEX idx_units_variant ON device_units(variant_id);
CREATE INDEX idx_units_status ON device_units(current_status);
CREATE INDEX idx_orders_customer ON rental_orders(customer_id);
CREATE INDEX idx_orders_staff ON rental_orders(staff_id);
CREATE INDEX idx_orders_status ON rental_orders(rental_order_status);
CREATE INDEX idx_orders_dates ON rental_orders(rental_start_date, expected_return_date);
CREATE INDEX idx_order_details_order ON rental_order_details(rental_order_id);
CREATE INDEX idx_order_details_variant ON rental_order_details(variant_id);
CREATE INDEX idx_order_units_detail ON rental_order_units(rental_order_detail_id);
CREATE INDEX idx_order_units_unit ON rental_order_units(unit_id);
CREATE INDEX idx_payments_order ON payments(rental_order_id);
CREATE INDEX idx_reviews_variant ON reviews(variant_id);
CREATE INDEX idx_reviews_customer ON reviews(customer_id);
CREATE INDEX idx_replies_review ON review_replies(review_id);
CREATE INDEX idx_returns_order ON return_records(rental_order_id);
CREATE INDEX idx_return_devices_unit ON return_devices(unit_id);


-- =========================================================
-- 10. SAMPLE DATA
-- =========================================================

-- Dữ liệu cơ bản
INSERT INTO equipment_categories (category_id, category_name, category_image) VALUES
(1, 'Thiết bị công nghệ', NULL),
(2, 'Điện thoại', NULL),
(3, 'Laptop', NULL),
(4, 'Máy ảnh', NULL),
(5, 'Phụ kiện quay chụp', NULL),
(6, 'Phụ kiện văn phòng', NULL);

INSERT INTO colors (color_id, color_name) VALUES
(1, 'Bạc'), (2, 'Đen'), (3, 'Xám Titan'), (4, 'Xám Không Gian'), (5, 'Xanh'), (6, 'Trắng'), (7, 'Cam');

INSERT INTO storage_capacities (capacity_id, capacity_value) VALUES
(1, '128GB'), (2, '256GB'), (3, '512GB'), (4, '1TB'), (5, 'Chỉ Body'), (6, 'Kèm lens 24-70mm'), (7, 'Không có'), (8, 'Bộ Creator');

-- Thiết bị & Phiên bản
INSERT INTO devices (device_id, device_name, manufacturer, description, default_image, category_id) VALUES
(1, 'iPhone 15 Pro Max', 'Apple', 'Điện thoại cao cấp của Apple.', 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800', 2),
(4, 'MacBook Pro 14 M3', 'Apple', 'Laptop hiệu năng cao.', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800', 3),
(7, 'Sony Alpha A7 IV', 'Sony', 'Máy ảnh mirrorless.', 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800', 4),
(8, 'GoPro Hero 12 Black', 'GoPro', 'Camera hành trình.', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800', 4);

INSERT INTO device_variants (variant_id, device_id, color_id, capacity_id, condition_name, daily_rental_price, deposit_amount) VALUES
(1, 1, 1, 2, 'New', 150000, 29490000),
(7, 4, 4, 3, 'New', 250000, 38990000),
(11, 7, 2, 5, 'New', 350000, 54990000),
(13, 8, 2, 5, 'New', 80000, 9990000);

-- Các Unit
INSERT INTO device_units (unit_id, variant_id, unit_code, serial_number, current_status, purchase_price) VALUES
(1, 1, 'IP15PM-256-001', 'APL001', 'rented', 29490000),
(10, 7, 'MBP14-M3-001', 'MBP001', 'rented', 38990000),
(15, 11, 'SONYA7IV-001', 'SONY001', 'available', 54990000),
(18, 13, 'GOPRO12-001', 'GOPRO001', 'available', 9990000);

-- Khách hàng & Nhân viên
INSERT INTO customers (customer_id, full_name, phone_number, email) VALUES
(1, 'Nguyễn Văn Nam', '0912345678', 'nam.nguyen@example.com'),
(2, 'Trần Thị Mai', '0987654321', 'mai.tran@example.com'),
(3, 'Lê Minh Tuấn', '0901234567', 'tuan.le@example.com');

INSERT INTO staff (staff_id, full_name, position_name) VALUES
(1, 'Nguyễn Văn Admin', 'Manager'),
(2, 'Trần Thị Nhân Viên', 'Sales Staff');

-- Đơn thuê (Đã gộp Invoices)
INSERT INTO rental_orders
(rental_order_id, order_code, customer_id, staff_id, rental_start_date, expected_return_date, rental_order_status, 
subtotal_amount, deposit_amount, penalty_amount, discount_amount, total_amount, payment_status, note) VALUES
(1, 'RO-2026-0001', 1, 2, '2026-06-25', '2026-06-27', 'active', 300000, 29490000, 0, 0, 29790000, 'paid', 'Thuê iPhone'),
(2, 'RO-2026-0002', 2, 2, '2026-06-28', '2026-06-30', 'confirmed', 500000, 38990000, 0, 0, 39490000, 'partial_paid', 'Thuê MacBook'),
(3, 'RO-2026-0003', 3, 1, '2026-06-21', '2026-06-22', 'completed', 350000, 54990000, 0, 0, 55340000, 'refunded', 'Thuê Sony A7 IV');

-- Chi tiết đơn thuê
INSERT INTO rental_order_details (rental_order_detail_id, rental_order_id, variant_id, rental_days, unit_rental_price, unit_deposit_amount) VALUES
(1, 1, 1, 2, 150000, 29490000),
(2, 2, 7, 2, 250000, 38990000),
(3, 3, 11, 1, 350000, 54990000);

-- Order Fees (Thay cho Invoice Items)
INSERT INTO order_fees (order_fee_id, rental_order_id, fee_type, description, quantity, unit_price, amount) VALUES
(1, 1, 'rental_fee', 'Tiền thuê iPhone 15 Pro Max 2 ngày', 2, 150000, 300000),
(2, 1, 'deposit', 'Tiền cọc iPhone 15 Pro Max', 1, 29490000, 29490000),
(3, 2, 'rental_fee', 'Tiền thuê MacBook Pro 14 M3 2 ngày', 2, 250000, 500000),
(4, 2, 'deposit', 'Tiền cọc MacBook Pro 14 M3', 1, 38990000, 38990000);

-- Payments
INSERT INTO payments (payment_id, rental_order_id, amount, payment_method, payment_type, payment_status) VALUES
(1, 1, 29790000, 'bank_transfer', 'payment', 'paid'),
(2, 2, 38990000, 'bank_transfer', 'deposit', 'paid'),
(3, 3, 54990000, 'cash', 'refund', 'refunded');

-- Reviews & Replies (Đã tách riêng)
INSERT INTO reviews (review_id, customer_id, rental_order_id, variant_id, equipment_rating, service_rating, comment) VALUES
(1, 1, 1, 1, 5, 5, 'Điện thoại còn rất mới, thủ tục thuê nhanh.'),
(2, 3, 3, 11, 5, 5, 'Sony A7 IV chụp đẹp, nhân viên hỗ trợ tốt.');

INSERT INTO review_replies (reply_id, review_id, customer_id, staff_id, reply_content) VALUES
(1, 2, NULL, 2, 'Cảm ơn anh đã sử dụng dịch vụ, hẹn gặp lại anh lần sau.');


-- =========================================================
-- 11. RESET IDENTITY SEQUENCES
-- =========================================================

SELECT setval(pg_get_serial_sequence('equipment_categories', 'category_id'), COALESCE((SELECT MAX(category_id) FROM equipment_categories), 1), true);
SELECT setval(pg_get_serial_sequence('devices', 'device_id'), COALESCE((SELECT MAX(device_id) FROM devices), 1), true);
SELECT setval(pg_get_serial_sequence('device_variants', 'variant_id'), COALESCE((SELECT MAX(variant_id) FROM device_variants), 1), true);
SELECT setval(pg_get_serial_sequence('device_units', 'unit_id'), COALESCE((SELECT MAX(unit_id) FROM device_units), 1), true);
SELECT setval(pg_get_serial_sequence('customers', 'customer_id'), COALESCE((SELECT MAX(customer_id) FROM customers), 1), true);
SELECT setval(pg_get_serial_sequence('staff', 'staff_id'), COALESCE((SELECT MAX(staff_id) FROM staff), 1), true);
SELECT setval(pg_get_serial_sequence('rental_orders', 'rental_order_id'), COALESCE((SELECT MAX(rental_order_id) FROM rental_orders), 1), true);
SELECT setval(pg_get_serial_sequence('rental_order_details', 'rental_order_detail_id'), COALESCE((SELECT MAX(rental_order_detail_id) FROM rental_order_details), 1), true);
SELECT setval(pg_get_serial_sequence('order_fees', 'order_fee_id'), COALESCE((SELECT MAX(order_fee_id) FROM order_fees), 1), true);
SELECT setval(pg_get_serial_sequence('payments', 'payment_id'), COALESCE((SELECT MAX(payment_id) FROM payments), 1), true);
SELECT setval(pg_get_serial_sequence('reviews', 'review_id'), COALESCE((SELECT MAX(review_id) FROM reviews), 1), true);
SELECT setval(pg_get_serial_sequence('review_replies', 'reply_id'), COALESCE((SELECT MAX(reply_id) FROM review_replies), 1), true);