-- =========================================================
-- TECH DEVICE RENTAL DATABASE - SUPABASE / POSTGRESQL
-- Bản đơn giản để dán trực tiếp vào Supabase SQL Editor
-- Không dùng function, trigger, extension hay thuật toán chống trùng lịch nâng cao.
--
-- Mục tiêu:
-- 1. Quản lý danh mục thiết bị công nghệ.
-- 2. Quản lý sản phẩm, phiên bản và từng thiết bị vật lý thật.
-- 3. Quản lý khách hàng, nhân viên, đơn thuê, trả thiết bị.
-- 4. Quản lý hóa đơn, thanh toán, tiền cọc, phí phạt.
-- 5. Quản lý giỏ hàng, yêu thích, đánh giá, bảo trì.
--
-- Lưu ý: Module bộ sản phẩm đã được loại bỏ theo phạm vi hiện tại của dự án.
-- Quy ước:
-- - Dùng lowercase_snake_case để tránh lỗi phân biệt hoa/thường trong PostgreSQL.
-- - Dữ liệu mẫu dùng id cố định để dễ hiểu quan hệ.
-- - Nếu bạn đã có bảng cũ, đoạn DROP bên dưới sẽ xóa và tạo lại từ đầu.
-- =========================================================


-- =========================================================
-- 0. DROP TABLES
-- =========================================================

DROP TABLE IF EXISTS maintenance_records CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS return_device_images CASCADE;
DROP TABLE IF EXISTS return_devices CASCADE;
DROP TABLE IF EXISTS return_records CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS invoice_items CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS rental_order_units CASCADE;
DROP TABLE IF EXISTS rental_order_details CASCADE;
DROP TABLE IF EXISTS rental_orders CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS device_images CASCADE;
DROP TABLE IF EXISTS device_units CASCADE;
DROP TABLE IF EXISTS device_variants CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS storage_capacities CASCADE;
DROP TABLE IF EXISTS colors CASCADE;
DROP TABLE IF EXISTS equipment_categories CASCADE;


-- =========================================================
-- 1. MASTER DATA: CATEGORY / COLOR / CAPACITY
-- =========================================================

-- Danh mục thiết bị.
-- parent_category_id dùng để tạo cây danh mục: Thiết bị -> Điện thoại -> iPhone.
CREATE TABLE equipment_categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL,
    category_image TEXT,
    parent_category_id INT REFERENCES equipment_categories(category_id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bảng màu dùng chung cho nhiều thiết bị.
CREATE TABLE colors (
    color_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color_name VARCHAR(100) NOT NULL UNIQUE
);

-- Bảng dung lượng/cấu hình dùng chung.
-- Có thể lưu: 128GB, 256GB, 512GB, Body only, Kèm lens 24-70mm, Không có...
CREATE TABLE storage_capacities (
    capacity_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacity_value VARCHAR(100) NOT NULL UNIQUE
);


-- =========================================================
-- 2. PRODUCT: DEVICE / VARIANT / UNIT / IMAGE
-- =========================================================

-- Thiết bị ở mức model chung.
-- Ví dụ: iPhone 15 Pro Max, MacBook Pro 14 M3, Sony A7 IV.
CREATE TABLE devices (
    device_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_name VARCHAR(255) NOT NULL,
    manufacturer VARCHAR(255),
    description TEXT,
    default_image TEXT,
    category_id INT REFERENCES equipment_categories(category_id) ON DELETE SET NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Phiên bản của thiết bị.
-- Ví dụ: iPhone 15 Pro Max / Bạc / 256GB / New.
-- Lưu giá thuê và tiền cọc mặc định tại đây.
CREATE TABLE device_variants (
    variant_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INT NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
    color_id INT REFERENCES colors(color_id) ON DELETE RESTRICT,
    capacity_id INT REFERENCES storage_capacities(capacity_id) ON DELETE RESTRICT,
    condition_name VARCHAR(100) NOT NULL DEFAULT 'New',
    daily_rental_price NUMERIC(12, 2) NOT NULL CHECK (daily_rental_price >= 0),
    deposit_amount NUMERIC(12, 2) NOT NULL CHECK (deposit_amount >= 0),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Tránh tạo trùng cùng một cấu hình của một thiết bị.
    UNIQUE (device_id, color_id, capacity_id, condition_name)
);

-- Thiết bị vật lý thật trong kho.
-- Đây là bảng quan trọng nhất cho hệ thống cho thuê.
-- Mỗi máy thật nên có serial/imei/unit_code riêng để biết khách thuê máy nào, trả máy nào.
CREATE TABLE device_units (
    unit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id INT NOT NULL REFERENCES device_variants(variant_id) ON DELETE CASCADE,
    unit_code VARCHAR(100) NOT NULL UNIQUE,
    serial_number VARCHAR(100) UNIQUE,
    imei VARCHAR(100) UNIQUE,
    current_status VARCHAR(50) NOT NULL DEFAULT 'available',
    current_condition VARCHAR(100) DEFAULT 'Good',
    purchase_price NUMERIC(12, 2) CHECK (purchase_price IS NULL OR purchase_price >= 0),
    purchase_date DATE,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Trạng thái đơn giản, dễ dùng trên UI.
    CHECK (current_status IN (
        'available',
        'reserved',
        'rented',
        'maintenance',
        'lost',
        'retired'
    ))
);

-- Ảnh thiết bị.
-- Có thể gắn ảnh theo thiết bị và theo màu.
CREATE TABLE device_images (
    image_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INT NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
    color_id INT REFERENCES colors(color_id) ON DELETE SET NULL,
    image_url TEXT NOT NULL,
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 3. USER: CUSTOMER / STAFF
-- =========================================================

-- Khách hàng.
-- Lưu ý: nếu làm sản phẩm thật, identity_number nên mã hóa hoặc hạn chế quyền truy cập.
CREATE TABLE customers (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    email VARCHAR(255) UNIQUE,
    address TEXT,
    password_hash VARCHAR(255),
    identity_number VARCHAR(50),
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (status IN ('active', 'locked', 'deleted'))
);

-- Nhân viên.
-- manager_id tự trỏ về staff để quản lý cấp trên - cấp dưới.
CREATE TABLE staff (
    staff_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255),
    position_name VARCHAR(100),
    manager_id INT REFERENCES staff(staff_id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (status IN ('active', 'locked', 'deleted'))
);


-- =========================================================
-- 4. RENTAL ORDER
-- =========================================================

-- Đơn thuê.
-- rental_order_status:
-- pending    : khách mới đặt, chưa xác nhận
-- confirmed  : đã xác nhận, có thể chuẩn bị thiết bị
-- active     : khách đang thuê
-- completed  : đã trả xong
-- cancelled  : đã hủy
CREATE TABLE rental_orders (
    rental_order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code VARCHAR(50) UNIQUE,
    customer_id INT REFERENCES customers(customer_id) ON DELETE SET NULL,
    staff_id INT REFERENCES staff(staff_id) ON DELETE SET NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    rental_start_date DATE NOT NULL,
    expected_return_date DATE NOT NULL,
    rental_order_status VARCHAR(50) DEFAULT 'pending',
    note TEXT,

    CHECK (expected_return_date >= rental_start_date),
    CHECK (rental_order_status IN (
        'pending',
        'confirmed',
        'active',
        'completed',
        'cancelled'
    ))
);

-- Chi tiết đơn thuê theo variant.
-- unit_rental_price và unit_deposit_amount là giá chốt tại thời điểm đặt,
-- không phụ thuộc việc sau này giá trong device_variants thay đổi.
CREATE TABLE rental_order_details (
    rental_order_detail_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_order_id INT NOT NULL REFERENCES rental_orders(rental_order_id) ON DELETE CASCADE,
    variant_id INT NOT NULL REFERENCES device_variants(variant_id) ON DELETE RESTRICT,
    rental_days INT NOT NULL CHECK (rental_days > 0),
    rental_quantity INT NOT NULL DEFAULT 1 CHECK (rental_quantity > 0),
    unit_rental_price NUMERIC(12, 2) NOT NULL CHECK (unit_rental_price >= 0),
    unit_deposit_amount NUMERIC(12, 2) NOT NULL CHECK (unit_deposit_amount >= 0),
    line_note TEXT,

    UNIQUE (rental_order_id, variant_id)
);

-- Gán thiết bị vật lý thật cho dòng đơn thuê.
-- Ví dụ: đơn thuê iPhone bạc 256GB số lượng 2 thì gán 2 unit_id cụ thể.
CREATE TABLE rental_order_units (
    rental_order_unit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_order_detail_id INT NOT NULL REFERENCES rental_order_details(rental_order_detail_id) ON DELETE CASCADE,
    unit_id INT NOT NULL REFERENCES device_units(unit_id) ON DELETE RESTRICT,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (rental_order_detail_id, unit_id)
);


-- =========================================================
-- 5. INVOICE / PAYMENT / DEPOSIT / PENALTY
-- =========================================================

-- Hóa đơn của đơn thuê.
CREATE TABLE invoices (
    invoice_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_code VARCHAR(50) UNIQUE,
    rental_order_id INT NOT NULL REFERENCES rental_orders(rental_order_id) ON DELETE CASCADE,
    subtotal_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (subtotal_amount >= 0),
    deposit_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (deposit_amount >= 0),
    penalty_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (penalty_amount >= 0),
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    invoice_status VARCHAR(50) DEFAULT 'unpaid',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (invoice_status IN ('unpaid', 'partial_paid', 'paid', 'refunded', 'cancelled'))
);

-- Dòng hóa đơn.
-- Dùng để tách tiền thuê, tiền cọc, phí phạt, hoàn cọc...
CREATE TABLE invoice_items (
    invoice_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INT NOT NULL REFERENCES invoices(invoice_id) ON DELETE CASCADE,
    item_type VARCHAR(50) NOT NULL,
    description TEXT,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (item_type IN ('rental_fee', 'deposit', 'penalty', 'damage_fee', 'refund', 'discount', 'other'))
);

-- Thanh toán.
-- Một hóa đơn có thể thanh toán nhiều lần: trả cọc trước, trả tiền thuê sau, hoàn cọc...
CREATE TABLE payments (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INT NOT NULL REFERENCES invoices(invoice_id) ON DELETE CASCADE,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    payment_method VARCHAR(100),
    payment_type VARCHAR(50) DEFAULT 'payment',
    payment_status VARCHAR(50) DEFAULT 'pending',
    transaction_code VARCHAR(100),
    paid_at TIMESTAMP,
    note TEXT,

    CHECK (payment_type IN ('payment', 'deposit', 'penalty', 'refund')),
    CHECK (payment_status IN ('pending', 'paid', 'failed', 'cancelled', 'refunded'))
);


-- =========================================================
-- 6. RETURN DEVICE
-- =========================================================

-- Phiếu trả thiết bị.
CREATE TABLE return_records (
    return_record_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_order_id INT REFERENCES rental_orders(rental_order_id) ON DELETE SET NULL,
    staff_id INT REFERENCES staff(staff_id) ON DELETE SET NULL,
    actual_return_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note TEXT
);

-- Thiết bị được trả theo từng unit_id.
-- Điều này giúp biết chính xác máy nào bị hư, máy nào mất, máy nào trả tốt.
CREATE TABLE return_devices (
    return_device_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_record_id INT NOT NULL REFERENCES return_records(return_record_id) ON DELETE CASCADE,
    unit_id INT NOT NULL REFERENCES device_units(unit_id) ON DELETE RESTRICT,
    return_condition VARCHAR(100) DEFAULT 'Good',
    damage_description TEXT,
    late_days INT DEFAULT 0 CHECK (late_days >= 0),
    penalty_fee NUMERIC(12, 2) DEFAULT 0 CHECK (penalty_fee >= 0),

    UNIQUE (return_record_id, unit_id)
);

-- Ảnh bằng chứng khi trả thiết bị.
CREATE TABLE return_device_images (
    image_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_device_id INT NOT NULL REFERENCES return_devices(return_device_id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 7. REVIEW
-- =========================================================

-- Đánh giá sản phẩm/dịch vụ.
-- parent_review_id dùng để reply bình luận.
-- Một review chỉ nên thuộc về khách hàng hoặc nhân viên, không phải cả hai.
CREATE TABLE reviews (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_review_id INT REFERENCES reviews(review_id) ON DELETE CASCADE,
    customer_id INT REFERENCES customers(customer_id) ON DELETE SET NULL,
    staff_id INT REFERENCES staff(staff_id) ON DELETE SET NULL,
    rental_order_id INT REFERENCES rental_orders(rental_order_id) ON DELETE SET NULL,
    variant_id INT REFERENCES device_variants(variant_id) ON DELETE SET NULL,
    equipment_rating INT CHECK (equipment_rating IS NULL OR equipment_rating BETWEEN 1 AND 5),
    service_rating INT CHECK (service_rating IS NULL OR service_rating BETWEEN 1 AND 5),
    comment TEXT NOT NULL,
    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (
        (customer_id IS NOT NULL AND staff_id IS NULL)
        OR
        (customer_id IS NULL AND staff_id IS NOT NULL)
    )
);


-- =========================================================
-- 8. CART / FAVORITES
-- =========================================================

-- Giỏ hàng.
-- Có thể dùng cho khách đăng nhập bằng customer_id hoặc khách vãng lai bằng session_id.
CREATE TABLE cart_items (
    cart_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255),
    customer_id INT REFERENCES customers(customer_id) ON DELETE CASCADE,
    variant_id INT NOT NULL REFERENCES device_variants(variant_id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL DEFAULT 'buy', -- 'buy', 'trial'
    quantity INT DEFAULT 1 CHECK (quantity > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (session_id IS NOT NULL OR customer_id IS NOT NULL)
);

-- Yêu thích.
CREATE TABLE favorites (
    favorite_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255),
    customer_id INT REFERENCES customers(customer_id) ON DELETE CASCADE,
    variant_id INT NOT NULL REFERENCES device_variants(variant_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (session_id IS NOT NULL OR customer_id IS NOT NULL)
);

-- PostgreSQL xem NULL là khác nhau, nên dùng partial unique index cho guest/customer.
CREATE UNIQUE INDEX unique_cart_guest
ON cart_items (session_id, variant_id, type)
WHERE customer_id IS NULL;

CREATE UNIQUE INDEX unique_cart_customer
ON cart_items (customer_id, variant_id, type)
WHERE customer_id IS NOT NULL;

CREATE UNIQUE INDEX unique_favorite_guest
ON favorites (session_id, variant_id)
WHERE customer_id IS NULL;

CREATE UNIQUE INDEX unique_favorite_customer
ON favorites (customer_id, variant_id)
WHERE customer_id IS NOT NULL;


-- =========================================================
-- 9. MAINTENANCE
-- =========================================================

-- Lịch sử bảo trì/sửa chữa thiết bị vật lý.
CREATE TABLE maintenance_records (
    maintenance_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id INT NOT NULL REFERENCES device_units(unit_id) ON DELETE CASCADE,
    staff_id INT REFERENCES staff(staff_id) ON DELETE SET NULL,
    maintenance_type VARCHAR(100),
    description TEXT,
    cost NUMERIC(12, 2) DEFAULT 0 CHECK (cost >= 0),
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_date TIMESTAMP,
    maintenance_status VARCHAR(50) DEFAULT 'open',
    note TEXT,

    CHECK (maintenance_status IN ('open', 'in_progress', 'completed', 'cancelled'))
);


-- =========================================================
-- 10. INDEXES
-- =========================================================

CREATE INDEX idx_categories_parent ON equipment_categories(parent_category_id);

CREATE INDEX idx_devices_category ON devices(category_id);
CREATE INDEX idx_devices_name ON devices(device_name);

CREATE INDEX idx_variants_device ON device_variants(device_id);
CREATE INDEX idx_variants_color ON device_variants(color_id);
CREATE INDEX idx_variants_capacity ON device_variants(capacity_id);

CREATE INDEX idx_units_variant ON device_units(variant_id);
CREATE INDEX idx_units_status ON device_units(current_status);

CREATE INDEX idx_orders_customer ON rental_orders(customer_id);
CREATE INDEX idx_orders_staff ON rental_orders(staff_id);
CREATE INDEX idx_orders_status ON rental_orders(rental_order_status);
CREATE INDEX idx_orders_dates ON rental_orders(rental_start_date, expected_return_date);

CREATE INDEX idx_order_details_order ON rental_order_details(rental_order_id);
CREATE INDEX idx_order_details_variant ON rental_order_details(variant_id);

CREATE INDEX idx_order_units_detail ON rental_order_units(rental_order_detail_id);
CREATE INDEX idx_order_units_unit ON rental_order_units(unit_id);

CREATE INDEX idx_invoices_order ON invoices(rental_order_id);
CREATE INDEX idx_payments_invoice ON payments(invoice_id);

CREATE INDEX idx_reviews_variant ON reviews(variant_id);
CREATE INDEX idx_reviews_customer ON reviews(customer_id);

CREATE INDEX idx_returns_order ON return_records(rental_order_id);
CREATE INDEX idx_return_devices_unit ON return_devices(unit_id);


-- =========================================================
-- 11. SAMPLE DATA
-- =========================================================

-- 11.1 Categories
INSERT INTO equipment_categories (category_id, category_name, category_image, parent_category_id) VALUES
(1, 'Thiết bị công nghệ', NULL, NULL),
(2, 'Điện thoại', NULL, 1),
(3, 'Laptop', NULL, 1),
(4, 'Máy ảnh', NULL, 1),
(5, 'Phụ kiện quay chụp', NULL, 1),
(6, 'Phụ kiện văn phòng', NULL, 1);

-- 11.2 Colors
INSERT INTO colors (color_id, color_name) VALUES
(1, 'Bạc'),
(2, 'Đen'),
(3, 'Xám Titan'),
(4, 'Xám Không Gian'),
(5, 'Xanh'),
(6, 'Trắng'),
(7, 'Cam');

-- 11.3 Capacities / Configurations
INSERT INTO storage_capacities (capacity_id, capacity_value) VALUES
(1, '128GB'),
(2, '256GB'),
(3, '512GB'),
(4, '1TB'),
(5, 'Chỉ Body'),
(6, 'Kèm lens 24-70mm'),
(7, 'Không có'),
(8, 'Bộ Creator');

-- 11.4 Devices
INSERT INTO devices (device_id, device_name, manufacturer, description, default_image, category_id) VALUES
(1, 'iPhone 15 Pro Max', 'Apple', 'Điện thoại cao cấp của Apple, phù hợp thuê đi du lịch, quay video, livestream.', 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800', 2),
(2, 'Samsung Galaxy S24 Ultra', 'Samsung', 'Flagship Samsung có bút S-Pen, camera zoom tốt, phù hợp quay chụp sự kiện.', 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800', 2),
(3, 'Google Pixel 8 Pro', 'Google', 'Điện thoại Android thuần, camera xử lý AI mạnh.', 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800', 2),
(4, 'MacBook Pro 14 M3', 'Apple', 'Laptop hiệu năng cao, phù hợp thiết kế, lập trình, dựng video.', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800', 3),
(5, 'Dell XPS 13 9340', 'Dell', 'Laptop doanh nhân mỏng nhẹ.', 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800', 3),
(6, 'ASUS ROG Zephyrus G14 OLED', 'ASUS', 'Laptop gaming và đồ họa màn OLED.', 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800', 3),
(7, 'Sony Alpha A7 IV', 'Sony', 'Máy ảnh mirrorless full-frame cho quay chụp chuyên nghiệp.', 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800', 4),
(8, 'GoPro Hero 12 Black', 'GoPro', 'Camera hành trình nhỏ gọn, chống rung tốt.', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800', 4),
(9, 'Rode Wireless PRO', 'Rode', 'Micro không dây cho vlogger, phỏng vấn, sự kiện.', 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800', 5),
(10, 'Elgato Ring Light', 'Elgato', 'Đèn livestream, hỗ trợ quay video trong phòng.', 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=800', 5),
(11, 'LG DualUp 28 Inch', 'LG', 'Màn hình tỉ lệ 16:18, phù hợp làm việc đa nhiệm.', 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800', 6),
(12, 'Logitech MX Master 3S', 'Logitech', 'Chuột văn phòng cao cấp.', 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800', 6);

-- 11.5 Variants
INSERT INTO device_variants
(variant_id, device_id, color_id, capacity_id, condition_name, daily_rental_price, deposit_amount) VALUES
(1, 1, 1, 2, 'New', 150000, 29490000),
(2, 1, 1, 3, 'New', 180000, 33990000),
(3, 1, 5, 2, 'New', 150000, 29490000),
(4, 2, 3, 2, 'New', 130000, 24990000),
(5, 2, 3, 3, 'New', 140000, 26990000),
(6, 3, 5, 1, 'New', 100000, 18990000),
(7, 4, 4, 3, 'New', 250000, 38990000),
(8, 4, 1, 4, 'New', 280000, 44990000),
(9, 5, 1, 3, 'New', 220000, 35490000),
(10, 6, 6, 4, 'New', 300000, 44990000),
(11, 7, 2, 5, 'New', 350000, 54990000),
(12, 7, 2, 6, 'New', 450000, 68990000),
(13, 8, 2, 5, 'New', 80000, 9990000),
(14, 9, 2, 7, 'New', 60000, 10500000),
(15, 10, 2, 7, 'New', 30000, 4500000),
(16, 11, 2, 7, 'New', 90000, 12900000),
(17, 12, 2, 7, 'New', 15000, 2490000);

-- 11.6 Physical Units
INSERT INTO device_units
(unit_id, variant_id, unit_code, serial_number, imei, current_status, current_condition, purchase_price, purchase_date, note) VALUES
(1, 1, 'IP15PM-256-SIL-001', 'APL15PM001', '350000000000001', 'rented', 'Good', 29490000, '2026-01-10', 'Đang cho khách thuê'),
(2, 1, 'IP15PM-256-SIL-002', 'APL15PM002', '350000000000002', 'available', 'Good', 29490000, '2026-01-10', NULL),
(3, 1, 'IP15PM-256-SIL-003', 'APL15PM003', '350000000000003', 'available', 'Good', 29490000, '2026-01-10', NULL),
(4, 2, 'IP15PM-512-SIL-001', 'APL15PM512001', '350000000000004', 'available', 'Good', 33990000, '2026-01-12', NULL),
(5, 3, 'IP15PM-256-BLU-001', 'APL15PMBLU001', '350000000000005', 'maintenance', 'Screen scratched', 29490000, '2026-01-12', 'Đang kiểm tra màn hình'),
(6, 4, 'SSS24U-256-TIT-001', 'SMS24U001', '351000000000001', 'available', 'Good', 24990000, '2026-02-05', NULL),
(7, 4, 'SSS24U-256-TIT-002', 'SMS24U002', '351000000000002', 'available', 'Good', 24990000, '2026-02-05', NULL),
(8, 5, 'SSS24U-512-TIT-001', 'SMS24U512001', '351000000000003', 'available', 'Good', 26990000, '2026-02-05', NULL),
(9, 6, 'PIX8P-128-BLU-001', 'GGPIX8P001', '352000000000001', 'available', 'Good', 18990000, '2026-02-20', NULL),
(10, 7, 'MBP14-M3-512-SG-001', 'MBP14M3001', NULL, 'rented', 'Good', 38990000, '2026-03-01', NULL),
(11, 7, 'MBP14-M3-512-SG-002', 'MBP14M3002', NULL, 'available', 'Good', 38990000, '2026-03-01', NULL),
(12, 8, 'MBP14-M3-1TB-SIL-001', 'MBP14M31TB001', NULL, 'available', 'Good', 44990000, '2026-03-03', NULL),
(13, 9, 'DELLXPS13-512-001', 'DLLXPS001', NULL, 'available', 'Good', 35490000, '2026-03-10', NULL),
(14, 10, 'ROGG14-1TB-001', 'ASUSROG001', NULL, 'available', 'Good', 44990000, '2026-03-15', NULL),
(15, 11, 'SONYA7IV-BODY-001', 'SONYA7IV001', NULL, 'available', 'Good', 54990000, '2026-04-01', NULL),
(16, 11, 'SONYA7IV-BODY-002', 'SONYA7IV002', NULL, 'available', 'Good', 54990000, '2026-04-01', NULL),
(17, 12, 'SONYA7IV-LENS-001', 'SONYA7IVL001', NULL, 'available', 'Good', 68990000, '2026-04-02', NULL),
(18, 13, 'GOPRO12-001', 'GOPRO12001', NULL, 'available', 'Good', 9990000, '2026-04-15', NULL),
(19, 13, 'GOPRO12-002', 'GOPRO12002', NULL, 'available', 'Good', 9990000, '2026-04-15', NULL),
(20, 14, 'RODEWPRO-001', 'RODE001', NULL, 'available', 'Good', 10500000, '2026-05-01', NULL),
(21, 14, 'RODEWPRO-002', 'RODE002', NULL, 'available', 'Good', 10500000, '2026-05-01', NULL),
(22, 15, 'ELGATO-RING-001', 'ELGATO001', NULL, 'available', 'Good', 4500000, '2026-05-05', NULL),
(23, 16, 'LGDUALUP-001', 'LGDU001', NULL, 'available', 'Good', 12900000, '2026-05-10', NULL),
(24, 17, 'MX3S-001', 'LOGIMX001', NULL, 'available', 'Good', 2490000, '2026-05-12', NULL);

-- 11.7 Images
INSERT INTO device_images (image_id, device_id, color_id, image_url, is_primary) VALUES
(1, 1, 1, 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800', TRUE),
(2, 1, 5, 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800', FALSE),
(3, 2, 3, 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800', TRUE),
(4, 4, 4, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800', TRUE),
(5, 7, 2, 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800', TRUE),
(6, 8, 2, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800', TRUE);

-- 11.8 Customers
INSERT INTO customers
(customer_id, full_name, phone_number, email, address, password_hash, identity_number, status) VALUES
(1, 'Nguyễn Văn Nam', '0912345678', 'nam.nguyen@example.com', 'Quận 1, TP. Hồ Chí Minh', '$2b$10$demo_hash_customer_1', '001095001234', 'active'),
(2, 'Trần Thị Mai', '0987654321', 'mai.tran@example.com', 'Quận Bình Thạnh, TP. Hồ Chí Minh', '$2b$10$demo_hash_customer_2', '002095005678', 'active'),
(3, 'Lê Minh Tuấn', '0901234567', 'tuan.le@example.com', 'Hải Châu, Đà Nẵng', '$2b$10$demo_hash_customer_3', '003095009012', 'active'),
(4, 'Hoàng Minh Anh', '0934567890', 'anh.hoang@example.com', 'Cầu Giấy, Hà Nội', '$2b$10$demo_hash_customer_4', '004095003456', 'active');

-- 11.9 Staff
INSERT INTO staff
(staff_id, full_name, phone_number, email, password_hash, position_name, manager_id, status) VALUES
(1, 'Nguyễn Văn Admin', '0999999999', 'admin@rentalservice.com', '$2b$10$demo_hash_admin', 'Manager', NULL, 'active'),
(2, 'Trần Thị Nhân Viên', '0988888888', 'staff1@rentalservice.com', '$2b$10$demo_hash_staff1', 'Sales Staff', 1, 'active'),
(3, 'Lê Hữu Kỹ Thuật', '0977777777', 'tech@rentalservice.com', '$2b$10$demo_hash_tech', 'Technician', 1, 'active');

-- 11.10 Rental Orders
INSERT INTO rental_orders
(rental_order_id, order_code, customer_id, staff_id, create_date, rental_start_date, expected_return_date, rental_order_status, note) VALUES
(1, 'RO-2026-0001', 1, 2, '2026-06-24 10:00:00', '2026-06-25', '2026-06-27', 'active', 'Khách thuê iPhone đi du lịch'),
(2, 'RO-2026-0002', 2, 2, '2026-06-24 11:30:00', '2026-06-28', '2026-06-30', 'confirmed', 'Khách thuê MacBook làm dự án ngắn hạn'),
(3, 'RO-2026-0003', 3, 1, '2026-06-20 09:15:00', '2026-06-21', '2026-06-22', 'completed', 'Khách đã trả Sony A7 IV'),
(4, 'RO-2026-0004', 4, NULL, '2026-06-25 14:00:00', '2026-07-01', '2026-07-03', 'pending', 'Đơn chờ nhân viên xác nhận');

-- 11.11 Rental Order Details
INSERT INTO rental_order_details
(rental_order_detail_id, rental_order_id, variant_id, rental_days, rental_quantity, unit_rental_price, unit_deposit_amount, line_note) VALUES
(1, 1, 1, 2, 1, 150000, 29490000, 'iPhone 15 Pro Max 256GB bạc'),
(2, 2, 7, 2, 1, 250000, 38990000, 'MacBook Pro 14 M3 512GB'),
(3, 3, 11, 1, 1, 350000, 54990000, 'Sony A7 IV body'),
(4, 4, 13, 2, 1, 80000, 9990000, 'GoPro Hero 12');

-- 11.12 Assign Physical Units
INSERT INTO rental_order_units
(rental_order_unit_id, rental_order_detail_id, unit_id, assigned_at) VALUES
(1, 1, 1, '2026-06-24 10:10:00'),
(2, 2, 10, '2026-06-24 11:45:00'),
(3, 3, 15, '2026-06-20 09:30:00');

-- 11.13 Invoices
INSERT INTO invoices
(invoice_id, invoice_code, rental_order_id, subtotal_amount, deposit_amount, penalty_amount, discount_amount, total_amount, invoice_status, created_at) VALUES
(1, 'INV-2026-0001', 1, 300000, 29490000, 0, 0, 29790000, 'paid', '2026-06-24 10:05:00'),
(2, 'INV-2026-0002', 2, 500000, 38990000, 0, 0, 39490000, 'partial_paid', '2026-06-24 11:35:00'),
(3, 'INV-2026-0003', 3, 350000, 54990000, 0, 0, 55340000, 'refunded', '2026-06-20 09:20:00'),
(4, 'INV-2026-0004', 4, 160000, 9990000, 0, 0, 10150000, 'unpaid', '2026-06-25 14:05:00');

-- 11.14 Invoice Items
INSERT INTO invoice_items
(invoice_item_id, invoice_id, item_type, description, quantity, unit_price, amount) VALUES
(1, 1, 'rental_fee', 'Tiền thuê iPhone 15 Pro Max 2 ngày', 2, 150000, 300000),
(2, 1, 'deposit', 'Tiền cọc iPhone 15 Pro Max', 1, 29490000, 29490000),
(3, 2, 'rental_fee', 'Tiền thuê MacBook Pro 14 M3 2 ngày', 2, 250000, 500000),
(4, 2, 'deposit', 'Tiền cọc MacBook Pro 14 M3', 1, 38990000, 38990000),
(5, 3, 'rental_fee', 'Tiền thuê Sony A7 IV 1 ngày', 1, 350000, 350000),
(6, 3, 'deposit', 'Tiền cọc Sony A7 IV', 1, 54990000, 54990000),
(7, 4, 'rental_fee', 'Tiền thuê GoPro Hero 12 2 ngày', 2, 80000, 160000),
(8, 4, 'deposit', 'Tiền cọc GoPro Hero 12', 1, 9990000, 9990000);

-- 11.15 Payments
INSERT INTO payments
(payment_id, invoice_id, amount, payment_method, payment_type, payment_status, transaction_code, paid_at, note) VALUES
(1, 1, 29790000, 'bank_transfer', 'payment', 'paid', 'BANK-0001', '2026-06-24 10:08:00', 'Khách đã thanh toán đủ'),
(2, 2, 38990000, 'bank_transfer', 'deposit', 'paid', 'BANK-0002', '2026-06-24 11:40:00', 'Khách mới thanh toán tiền cọc'),
(3, 3, 55340000, 'cash', 'payment', 'paid', 'CASH-0003', '2026-06-20 09:25:00', 'Khách thanh toán khi nhận máy'),
(4, 3, 54990000, 'cash', 'refund', 'refunded', 'REFUND-0003', '2026-06-22 17:20:00', 'Hoàn cọc sau khi trả máy tốt');

-- 11.16 Return Records
INSERT INTO return_records
(return_record_id, rental_order_id, staff_id, actual_return_date, note) VALUES
(1, 3, 1, '2026-06-22 17:00:00', 'Khách trả đúng hạn, máy hoạt động tốt');

INSERT INTO return_devices
(return_device_id, return_record_id, unit_id, return_condition, damage_description, late_days, penalty_fee) VALUES
(1, 1, 15, 'Good', NULL, 0, 0);

INSERT INTO return_device_images
(image_id, return_device_id, image_url) VALUES
(1, 1, 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800');

-- 11.17 Reviews
INSERT INTO reviews
(review_id, parent_review_id, customer_id, staff_id, rental_order_id, variant_id, equipment_rating, service_rating, comment, review_date) VALUES
(1, NULL, 1, NULL, 1, 1, 5, 5, 'Điện thoại còn rất mới, thủ tục thuê nhanh.', '2026-06-24 15:00:00'),
(2, NULL, 3, NULL, 3, 11, 5, 5, 'Sony A7 IV chụp đẹp, pin đầy đủ, nhân viên hỗ trợ tốt.', '2026-06-22 18:00:00'),
(3, 2, NULL, 2, 3, 11, NULL, NULL, 'Cảm ơn anh đã sử dụng dịch vụ, hẹn gặp lại anh lần sau.', '2026-06-22 18:10:00');

-- 11.18 Cart / Favorites
INSERT INTO cart_items
(cart_item_id, session_id, customer_id, variant_id, quantity) VALUES
(1, NULL, 1, 13, 1),
(2, 'guest-session-001', NULL, 14, 1);

INSERT INTO favorites
(favorite_id, session_id, customer_id, variant_id) VALUES
(1, NULL, 1, 7),
(2, 'guest-session-001', NULL, 1);

-- 11.19 Maintenance
INSERT INTO maintenance_records
(maintenance_id, unit_id, staff_id, maintenance_type, description, cost, start_date, end_date, maintenance_status, note) VALUES
(1, 5, 3, 'Kiểm tra màn hình', 'Màn hình có vết xước nhẹ sau lần thuê trước.', 0, '2026-06-24 08:00:00', NULL, 'in_progress', 'Đang chờ kỹ thuật xác nhận có cần thay kính hay không');


-- =========================================================
-- 12. RESET IDENTITY SEQUENCES
-- Sau khi insert id cố định, reset sequence để lần insert tiếp theo không bị trùng id.
-- =========================================================

SELECT setval(pg_get_serial_sequence('equipment_categories', 'category_id'), COALESCE((SELECT MAX(category_id) FROM equipment_categories), 1), true);
SELECT setval(pg_get_serial_sequence('colors', 'color_id'), COALESCE((SELECT MAX(color_id) FROM colors), 1), true);
SELECT setval(pg_get_serial_sequence('storage_capacities', 'capacity_id'), COALESCE((SELECT MAX(capacity_id) FROM storage_capacities), 1), true);
SELECT setval(pg_get_serial_sequence('devices', 'device_id'), COALESCE((SELECT MAX(device_id) FROM devices), 1), true);
SELECT setval(pg_get_serial_sequence('device_variants', 'variant_id'), COALESCE((SELECT MAX(variant_id) FROM device_variants), 1), true);
SELECT setval(pg_get_serial_sequence('device_units', 'unit_id'), COALESCE((SELECT MAX(unit_id) FROM device_units), 1), true);
SELECT setval(pg_get_serial_sequence('device_images', 'image_id'), COALESCE((SELECT MAX(image_id) FROM device_images), 1), true);
SELECT setval(pg_get_serial_sequence('customers', 'customer_id'), COALESCE((SELECT MAX(customer_id) FROM customers), 1), true);
SELECT setval(pg_get_serial_sequence('staff', 'staff_id'), COALESCE((SELECT MAX(staff_id) FROM staff), 1), true);
SELECT setval(pg_get_serial_sequence('rental_orders', 'rental_order_id'), COALESCE((SELECT MAX(rental_order_id) FROM rental_orders), 1), true);
SELECT setval(pg_get_serial_sequence('rental_order_details', 'rental_order_detail_id'), COALESCE((SELECT MAX(rental_order_detail_id) FROM rental_order_details), 1), true);
SELECT setval(pg_get_serial_sequence('rental_order_units', 'rental_order_unit_id'), COALESCE((SELECT MAX(rental_order_unit_id) FROM rental_order_units), 1), true);
SELECT setval(pg_get_serial_sequence('invoices', 'invoice_id'), COALESCE((SELECT MAX(invoice_id) FROM invoices), 1), true);
SELECT setval(pg_get_serial_sequence('invoice_items', 'invoice_item_id'), COALESCE((SELECT MAX(invoice_item_id) FROM invoice_items), 1), true);
SELECT setval(pg_get_serial_sequence('payments', 'payment_id'), COALESCE((SELECT MAX(payment_id) FROM payments), 1), true);
SELECT setval(pg_get_serial_sequence('return_records', 'return_record_id'), COALESCE((SELECT MAX(return_record_id) FROM return_records), 1), true);
SELECT setval(pg_get_serial_sequence('return_devices', 'return_device_id'), COALESCE((SELECT MAX(return_device_id) FROM return_devices), 1), true);
SELECT setval(pg_get_serial_sequence('return_device_images', 'image_id'), COALESCE((SELECT MAX(image_id) FROM return_device_images), 1), true);
SELECT setval(pg_get_serial_sequence('reviews', 'review_id'), COALESCE((SELECT MAX(review_id) FROM reviews), 1), true);
SELECT setval(pg_get_serial_sequence('cart_items', 'cart_item_id'), COALESCE((SELECT MAX(cart_item_id) FROM cart_items), 1), true);
SELECT setval(pg_get_serial_sequence('favorites', 'favorite_id'), COALESCE((SELECT MAX(favorite_id) FROM favorites), 1), true);
SELECT setval(pg_get_serial_sequence('maintenance_records', 'maintenance_id'), COALESCE((SELECT MAX(maintenance_id) FROM maintenance_records), 1), true);


-- =========================================================
-- 13. QUICK CHECK QUERIES
-- Có thể chạy thử sau khi import để xem dữ liệu.
-- =========================================================

-- Danh sách thiết bị + variant + số lượng unit theo trạng thái.
-- SELECT
--     d.device_name,
--     c.color_name,
--     sc.capacity_value,
--     dv.condition_name,
--     du.current_status,
--     COUNT(*) AS unit_count
-- FROM device_units du
-- JOIN device_variants dv ON dv.variant_id = du.variant_id
-- JOIN devices d ON d.device_id = dv.device_id
-- LEFT JOIN colors c ON c.color_id = dv.color_id
-- LEFT JOIN storage_capacities sc ON sc.capacity_id = dv.capacity_id
-- GROUP BY d.device_name, c.color_name, sc.capacity_value, dv.condition_name, du.current_status
-- ORDER BY d.device_name, du.current_status;

-- Danh sách đơn thuê.
-- SELECT
--     ro.order_code,
--     cu.full_name AS customer_name,
--     ro.rental_start_date,
--     ro.expected_return_date,
--     ro.rental_order_status,
--     i.total_amount,
--     i.invoice_status
-- FROM rental_orders ro
-- LEFT JOIN customers cu ON cu.customer_id = ro.customer_id
-- LEFT JOIN invoices i ON i.rental_order_id = ro.rental_order_id
-- ORDER BY ro.rental_order_id;

-- =========================================================
-- END OF FILE
-- =========================================================
